schema_version = 1

[common]
process = "dy"
process_name = "dy"
n_loops = 1
final_state = ["a"]
channel = [1, 0]
diagrams = []
process_basename = "DY_QG_S1000_CM_H_EXACT_AUX_20260915"
verbosity = "info"
skip_ps_validation = true

[common.kinematics]
m_top = 173.0
m_higgs = 125.0
pg1 = [500.0, 0.0, 0.0, 500.0]
pg2 = [500.0, 0.0, 0.0, -500.0]
helicities = [1, 1, 0, 0, 0]

[common.scales]
muv = 1000.0
lambda_sq = 8302.489924
mur_sq = 8302.489924

[common.initial_state]
external_gluon_polarisation = true
symmetrise_p1_p2 = true

[common.precision]
fallback_precision = 32

[common.gammaloop]
generation_configuration = "/home/zeno/DY/pygloop_6c15087/configs/DY/generate.toml"
runtime_configuration = "/home/zeno/DY/pygloop_6c15087/configs/DY/runtime.toml"
settings = []
general_settings = []

[generate]
clean = false
generation_type = "gammaloop"
parallel_graphs = 4
enable_integrated_uv_counterterms = true
top_self_energy_renormalisation = "no-os"
check_generation_limits = false
threshold_h_function = "gaussian"

[integrate]
implementation = "zenos"
parameterisation = "spherical"
multi_channeling = true
integrator = "symbolica"
iterations = 100
points_per_iteration = 1000000
cores = 64
seed = 915220000
phase = "real"
restart = false
workspace_name = "dy_cm_exact_aux_20260915_inclusive_qg"

[integrate.runtime_parameters]
m_top = "173"
muv = "1000"
lambda_sq = "8302.489924"
mur_sq = "8302.489924"
alpha_s = "0.118"
alpha_ew_inverse = "132.507"
zmin = "0"
zmax = "1"

[integrate.selection]
integrated_uv_counterterms = "all"

[integrate.stability]
rotation_check_digits = 7
rotation_check_count = 2
rotation_check_eps = 1.0e-15
rotation_check_arb_digits = 32
backend = "double-float"
theta_tolerance = 0.0
large_weight_precision = 3.0426869845409606e-12

[integrate.beams]
enabled = true
parameterisation = "x1_x2"
z_bin = [0.00, 1.00]
q_min = 300.0
physical_normalisation = true
integrated_leptonic_phase_space = true

[integrate.beams.pdf]
set = "PDF4LHC21_40"
member = 0
muf_sq = 8302.489924

[integrate.beams.scheme_counterterm]
enabled = true
sobol_power = 18
replicas = 8

[integrate.decoupling]
enabled = false

